// <auto-generated />
using System;
using Laison.Lapis.Prepayment.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Volo.Abp.EntityFrameworkCore;

namespace Laison.Lapis.Prepayment.Migrations
{
    [DbContext(typeof(PrepaymentHttpApiHostMigrationsDbContext))]
    [Migration("20210411113611_init2")]
    partial class init2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.MySql)
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Laison.Lapis.Prepayment.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40) CHARACTER SET utf8mb4")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreationTime");

                    b.Property<double>("Debt")
                        .HasColumnType("double");

                    b.Property<string>("ExtraProperties")
                        .HasColumnType("longtext CHARACTER SET utf8mb4")
                        .HasColumnName("ExtraProperties");

                    b.Property<bool>("MakeCard")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("No")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("Laison.Lapis.Prepayment.Domain.Entities.RechargeTradeDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40) CHARACTER SET utf8mb4")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreationTime");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ExtraProperties")
                        .HasColumnType("longtext CHARACTER SET utf8mb4")
                        .HasColumnName("ExtraProperties");

                    b.Property<string>("InvoiceNo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("recharge_trade_detail");
                });

            modelBuilder.Entity("Laison.Lapis.Prepayment.Domain.Entities.RegisterTradeDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40) CHARACTER SET utf8mb4")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreationTime");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ExtraProperties")
                        .HasColumnType("longtext CHARACTER SET utf8mb4")
                        .HasColumnName("ExtraProperties");

                    b.Property<string>("InvoiceNo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("char(36)");

                    b.Property<double>("RegisterCharge")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("register_trade_detail");
                });

            modelBuilder.Entity("Laison.Lapis.Prepayment.Domain.Entities.Account", b =>
                {
                    b.OwnsOne("Laison.Lapis.Prepayment.Domain.Entities.Customer", "Customer", b1 =>
                        {
                            b1.Property<Guid>("AccountId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Email")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.Property<string>("IdentityNo")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.Property<string>("Name")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.Property<string>("Telephone")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.HasKey("AccountId");

                            b1.ToTable("customer");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");

                            b1.OwnsOne("Laison.Lapis.Prepayment.Domain.ValueObjects.Address", "Address", b2 =>
                                {
                                    b2.Property<Guid>("CustomerAccountId")
                                        .HasColumnType("char(36)");

                                    b2.Property<string>("City")
                                        .HasColumnType("longtext CHARACTER SET utf8mb4")
                                        .HasColumnName("AddressCity");

                                    b2.Property<string>("Province")
                                        .HasColumnType("longtext CHARACTER SET utf8mb4")
                                        .HasColumnName("AddressProvince");

                                    b2.Property<string>("Town")
                                        .HasColumnType("longtext CHARACTER SET utf8mb4")
                                        .HasColumnName("AddressTown");

                                    b2.Property<string>("Village")
                                        .HasColumnType("longtext CHARACTER SET utf8mb4")
                                        .HasColumnName("AddressVillage");

                                    b2.HasKey("CustomerAccountId");

                                    b2.ToTable("customer");

                                    b2.WithOwner()
                                        .HasForeignKey("CustomerAccountId");
                                });

                            b1.Navigation("Address");
                        });

                    b.Navigation("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
